# Generated by Django 5.1 on 2024-09-05 23:46

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('console_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('console_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game_info',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('consoles', models.ManyToManyField(to='gameinfo.console')),
            ],
            options={
                'ordering': ['game_name'],
            },
            managers=[
                ('seasonal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Extra_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('rating', models.CharField(choices=[('E', 'Everyone'), ('E+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature 17+'), ('A', 'Adults only 18+'), ('RP', 'rating pending')], max_length=2)),
                ('source', models.CharField(max_length=100)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.game_info')),
            ],
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('dev_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dev_name', models.CharField(max_length=100)),
                ('game_infos', models.ManyToManyField(to='gameinfo.game_info')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=100)),
                ('game_infos', models.ManyToManyField(to='gameinfo.game_info')),
            ],
        ),
        migrations.CreateModel(
            name='Hype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.game_info')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=100)),
                ('game_infos', models.ManyToManyField(to='gameinfo.game_info')),
            ],
        ),
        migrations.CreateModel(
            name='Release_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_season', models.CharField(max_length=30)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.game_info')),
            ],
        ),
    ]
