# Generated by Django 5.1 on 2024-09-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0002_hype_is_hype_hype_maybe_hype_hype_not_hype'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game_info',
            managers=[
            ],
        ),
    ]
