# Generated by Django 5.1 on 2024-09-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0003_alter_game_info_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release_time',
            name='release_season',
        ),
    ]
