# Generated by Django 5.1 on 2024-09-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0004_remove_release_time_release_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_time',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='release_time',
            name='release_season',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
