# Generated by Django 5.1 on 2024-09-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0005_release_time_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release_time',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='release_time',
            name='release_season',
            field=models.CharField(max_length=30),
        ),
    ]
