# Generated by Django 5.1 on 2024-09-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0006_alter_release_time_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release_time',
            name='release_date',
        ),
    ]
