# Generated by Django 5.1 on 2024-09-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0007_remove_release_time_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='console_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game_info',
            name='game_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
