# Generated by Django 5.1 on 2024-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0008_alter_console_console_id_alter_game_info_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_info',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
