# Generated by Django 5.1 on 2024-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0009_alter_extra_info_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='dev_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
