# Generated by Django 5.1 on 2024-09-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0011_alter_console_console_name_alter_dev_dev_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_info',
            name='rating',
        ),
        migrations.AlterField(
            model_name='extra_info',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
