# Generated by Django 5.1 on 2024-09-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0012_remove_extra_info_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_time',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
