# Generated by Django 5.1 on 2024-09-08 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0014_remove_release_time_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_time',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
