# Generated by Django 5.1 on 2024-09-08 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0016_rename_release_season_release_time_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release_time',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
