# Generated by Django 5.1.1 on 2024-09-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0019_hype_average_hype'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
