# Generated by Django 5.1.1 on 2024-09-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0022_rename_screen_shot_id_screenshots_screenshot_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='Screenshot',
        ),
    ]
